[workspace]
resolver = "2"
members = [
  "lang1",
  "frontend",
  "lang3",
  "logic",
  "watch",
  #"codegen",
  "codegen_ir",
  "codegen_llvm",
  "codegen_interp",
  "data",
  #"freestanding"
]

[profile.release]
lto = true
debug = 1
incremental = false
