[package]
name = "protolang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
codespan = "0.11"
nom = "7"
nom_locate = "4"
anyhow = { version = "1", feature = ["backtrace"] }
rustyline = "9.1"
