[workspace]
members = [
  "lang1",
  "frontend",
  "lang3",
  "logic",
  #"codegen",
  "codegen_ir",
  "codegen_llvm",
  "codegen_interp",
  "data"
]

[profile.release]
lto = true
debug = 1
incremental = false
